---
- hosts: all
  become: yes
  remote_user: devops_user
  vars_files:
    - vars/external_vars.yml
  roles:
    - { role: configuration, tags: ["configuration"] }

- hosts: app_server
  remote_user: devops_user
  vars_files:
    - vars/external_vars.yml
  roles:
    - { role: php, tags: ["install"] }
    - { role: docker, tags: ["install"] }

#  tasks:
#    - name: Include congurate
#      include_tasks: main/tasks/congurate_host.yml
#    - name: Include composer
#      include_tasks: main/tasks/composer.yml
#      args:
#        apply:
#          tags:
#            - install