---

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: ansible_os_family {{ ansible_os_family }} ansible_distribution_major_version {{ ansible_distribution }}


# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-openSUSETumbleweed.yml
  when: ansible_distribution == 'openSUSE Tumbleweed'


# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml