---
- name: Add PHP repository
  become: yes
  community.general.zypper_repository:
    name: openSUSE:Factory
    repo: 'https://download.opensuse.org/tumbleweed/repo/oss/'
    state: present
- name: Remove PHP 8
  become: yes
  community.general.zypper:
    name: php8
    state: removed
- name: Install PHP {{ php_version }} and Magento PHP Dependencies
  become: yes
  community.general.zypper:
    name: [
        "php{{ php_version }}",
        "php{{ php_version }}-fpm",
        "php{{ php_version }}-bcmath",
        "php{{ php_version }}-curl",
        "php{{ php_version }}-dom",
        "php{{ php_version }}-gd",
        "php{{ php_version }}-iconv",
        "php{{ php_version }}-intl",
        "php{{ php_version }}-mbstring",
        "php{{ php_version }}-mysql",
      #        "php{{ php_version }}-simplexml",
        "php{{ php_version }}-soap",
        "php{{ php_version }}-xsl",
        "php{{ php_version }}-zip",
        "phpMyAdmin"
    ]
    state: latest

- name: Prepare php-fpm configuration
  become: yes
  shell: cp -v /etc/php7/fpm/php-fpm.conf.default /etc/php7/fpm/php-fpm.conf && cp -v /etc/php7/fpm/php-fpm.d/www.conf.default /etc/php7/fpm/php-fpm.d/www.conf


- name: Make sure a service php-fpm is running
  become: yes
  ansible.builtin.systemd:
    enabled: yes
    state: started
    name: php-fpm